on:
  push:

jobs:
  check-skip-ci:
    name: Insanity Check
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - run: echo check-skip-ci
  build-and-publish:
    needs: check-skip-ci
    runs-on: ubuntu-latest
    steps:
      - run: echo build-and-publish
    
